import envParse from "@/utils/env";
import type { Metadata } from "next";
import { Toaster } from "react-hot-toast";
import "./globals.css";

export const metadata: Metadata = {
    title: "Quesher.com",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    envParse();
    return (
        <html lang="en">
            <body>
                {children}
                <Toaster position="top-right" />
            </body>
        </html>
    );
}
